---
title: "Covid19 Analysis"
output: html_notebook
---

bullets:
corona deaths 
sentinel
cases, ratio etc
hospital beds
pcr-test-statistics
comparison different countries

Stand 22.08.2020

This paper summarizes data of Covid19 (SARS-Cov2).

pcr herstelleung: siemens, qiagen, roche

spez = 99.8% (diagnostics) (richtig positiv/falsch positiv)

spezifität / sensitivität PCR Test


```{r package imports, include=FALSE}
#install.packages("tidyverse")
#install.packages("lubridate")
#install.packages("kableExtra")
library("tidyverse")
#library("lubridate")
#library("kableExtra")
```

# Total deaths Germany

```{r}
#test_pos <- read.csv("data/csv/q1_1111.csv", header = TRUE, stringsAsFactors = FALSE)
total_deaths <- read.table(file = "data/tsv/demo_mmonth.tsv", sep = "\t", header = TRUE)
sterbefaelle_DE <- read.table(file = "data/sterbefaelle_DE.xlsx", header = TRUE)
sterbefaelle_DE_2020_tage <- read.table(file = "data/sterbefaelle_2020_DE.xlsx", header = TRUE)


```

```{r}
total_deaths_DE <- total_deaths %>% 
  filter(grepl("DE", unit.month.geo.time, fixed = TRUE))
```










